#!/usr/bin/env python3
"""
Script to add notification localization entries.
Run this on Railway after deployment.
Usage: railway run python3 add_notification_localizations.py
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Notification localization entries
NOTIFICATION_LOCALIZATIONS = {
    'notifications.title': {
        'description': 'Notifications panel title',
        'en': 'Notifications',
        'de': 'Benachrichtigungen',
        'es': 'Notificaciones',
        'fr': 'Notifications',
        'it': 'Notifiche',
        'pt': 'Notificações',
        'ru': 'Уведомления',
        'tr': 'Bildirimler',
        'ka': 'შეტყობინებები',
        'nl': 'Meldingen',
        'sv': 'Aviseringar',
        'no': 'Varsler',
        'da': 'Notifikationer',
        'fi': 'Ilmoitukset',
        'pl': 'Powiadomienia',
        'cs': 'Oznámení',
        'sk': 'Upozornenia',
        'hu': 'Értesítések',
        'ro': 'Notificări',
        'bg': 'Известия',
        'el': 'Ειδοποιήσεις',
        'uk': 'Сповіщення',
        'zh': '通知',
        'ja': '通知',
        'ko': '알림',
        'hi': 'सूचनाएं',
        'ur': 'اطلاعات',
        'id': 'Notifikasi',
        'ms': 'Pemberitahuan',
        'th': 'การแจ้งเตือน',
        'vi': 'Thông báo',
        'fa': 'اعلان\u200cها',
        'ar': 'الإشعارات',
        'sw': 'Arifa',
    },
    'notifications.mark_all_read': {
        'description': 'Mark all notifications as read button',
        'en': 'Mark all as read',
        'de': 'Alle als gelesen',
        'es': 'Marcar todo como leído',
        'fr': 'Tout marquer comme lu',
        'it': 'Segna tutto come letto',
        'pt': 'Marcar tudo como lido',
        'ru': 'Отметить все как прочитанные',
        'tr': 'Tümünü okundu işaretle',
        'ka': 'ყველა მონიშნე როგორც წაკითხული',
        'nl': 'Alles als gelezen markeren',
        'sv': 'Märk alla som lästa',
        'no': 'Merk alle som lest',
        'da': 'Marker alle som læst',
        'fi': 'Merkitse kaikki luetuksi',
        'pl': 'Oznacz wszystkie jako przeczytane',
        'cs': 'Označit vše jako přečtené',
        'sk': 'Označiť všetko ako prečítané',
        'hu': 'Összes megjelölése olvasottként',
        'ro': 'Marchează totul ca citit',
        'bg': 'Маркирай всички като прочетени',
        'el': 'Σήμανση όλων ως αναγνωσμένων',
        'uk': 'Позначити все як прочитане',
        'zh': '全部标记为已读',
        'ja': 'すべて既読にする',
        'ko': '모두 읽음으로 표시',
        'hi': 'सभी को पढ़ा हुआ चिह्नित करें',
        'ur': 'سب کو پڑھا ہوا نشان زد کریں',
        'id': 'Tandai semua sebagai dibaca',
        'ms': 'Tandakan semua sebagai dibaca',
        'th': 'ทำเครื่องหมายทั้งหมดว่าอ่านแล้ว',
        'vi': 'Đánh dấu tất cả là đã đọc',
        'fa': 'علامت\u200cگذاری همه به عنوان خوانده شده',
        'ar': 'تعليم الكل كمقروء',
        'sw': 'Weka zote kama zimesomwa',
    },
    'notifications.loading': {
        'description': 'Loading notifications message',
        'en': 'Loading notifications...',
        'de': 'Lade Benachrichtigungen...',
        'es': 'Cargando notificaciones...',
        'fr': 'Chargement des notifications...',
        'it': 'Caricamento notifiche...',
        'pt': 'Carregando notificações...',
        'ru': 'Загрузка уведомлений...',
        'tr': 'Bildirimler yükleniyor...',
        'ka': 'შეტყობინებების ჩატვირთვა...',
        'nl': 'Meldingen laden...',
        'sv': 'Laddar aviseringar...',
        'no': 'Laster varsler...',
        'da': 'Indlæser notifikationer...',
        'fi': 'Ladataan ilmoituksia...',
        'pl': 'Ładowanie powiadomień...',
        'cs': 'Načítání oznámení...',
        'sk': 'Načítanie upozornení...',
        'hu': 'Értesítések betöltése...',
        'ro': 'Se încarcă notificările...',
        'bg': 'Зареждане на известия...',
        'el': 'Φόρτωση ειδοποιήσεων...',
        'uk': 'Завантаження сповіщень...',
        'zh': '正在加载通知...',
        'ja': '通知を読み込み中...',
        'ko': '알림 로딩 중...',
        'hi': 'सूचनाएं लोड हो रही हैं...',
        'ur': 'اطلاعات لوڈ ہو رہی ہیں...',
        'id': 'Memuat notifikasi...',
        'ms': 'Memuatkan pemberitahuan...',
        'th': 'กำลังโหลดการแจ้งเตือน...',
        'vi': 'Đang tải thông báo...',
        'fa': 'در حال بارگذاری اعلان\u200cها...',
        'ar': 'جاري تحميل الإشعارات...',
        'sw': 'Inapakia arifa...',
    },
    'notifications.empty': {
        'description': 'Empty notifications message',
        'en': 'No notifications',
        'de': 'Keine Benachrichtigungen',
        'es': 'Sin notificaciones',
        'fr': 'Aucune notification',
        'it': 'Nessuna notifica',
        'pt': 'Sem notificações',
        'ru': 'Нет уведомлений',
        'tr': 'Bildirim yok',
        'ka': 'შეტყობინებები არ არის',
        'nl': 'Geen meldingen',
        'sv': 'Inga aviseringar',
        'no': 'Ingen varsler',
        'da': 'Ingen notifikationer',
        'fi': 'Ei ilmoituksia',
        'pl': 'Brak powiadomień',
        'cs': 'Žádná oznámení',
        'sk': 'Žiadne upozornenia',
        'hu': 'Nincsenek értesítések',
        'ro': 'Fără notificări',
        'bg': 'Няма известия',
        'el': 'Δεν υπάρχουν ειδοποιήσεις',
        'uk': 'Немає сповіщень',
        'zh': '没有通知',
        'ja': '通知はありません',
        'ko': '알림 없음',
        'hi': 'कोई सूचना नहीं',
        'ur': 'کوئی اطلاعات نہیں',
        'id': 'Tidak ada notifikasi',
        'ms': 'Tiada pemberitahuan',
        'th': 'ไม่มีการแจ้งเตือน',
        'vi': 'Không có thông báo',
        'fa': 'اعلانی وجود ندارد',
        'ar': 'لا توجد إشعارات',
        'sw': 'Hakuna arifa',
    },
    'notifications.load_error': {
        'description': 'Error loading notifications message',
        'en': 'Error loading notifications',
        'de': 'Fehler beim Laden der Benachrichtigungen',
        'es': 'Error al cargar notificaciones',
        'fr': 'Erreur lors du chargement des notifications',
        'it': 'Errore nel caricamento delle notifiche',
        'pt': 'Erro ao carregar notificações',
        'ru': 'Ошибка загрузки уведомлений',
        'tr': 'Bildirimler yüklenirken hata',
        'ka': 'შეტყობინებების ჩატვირთვის შეცდომა',
        'nl': 'Fout bij het laden van meldingen',
        'sv': 'Fel vid laddning av aviseringar',
        'no': 'Feil ved lasting av varsler',
        'da': 'Fejl ved indlæsning af notifikationer',
        'fi': 'Virhe ilmoitusten lataamisessa',
        'pl': 'Błąd podczas ładowania powiadomień',
        'cs': 'Chyba při načítání oznámení',
        'sk': 'Chyba pri načítaní upozornení',
        'hu': 'Hiba az értesítések betöltésekor',
        'ro': 'Eroare la încărcarea notificărilor',
        'bg': 'Грешка при зареждане на известия',
        'el': 'Σφάλμα κατά τη φόρτωση ειδοποιήσεων',
        'uk': 'Помилка завантаження сповіщень',
        'zh': '加载通知时出错',
        'ja': '通知の読み込みエラー',
        'ko': '알림 로딩 오류',
        'hi': 'सूचनाएं लोड करने में त्रुटि',
        'ur': 'اطلاعات لوڈ کرنے میں خرابی',
        'id': 'Kesalahan memuat notifikasi',
        'ms': 'Ralat memuatkan pemberitahuan',
        'th': 'ข้อผิดพลาดในการโหลดการแจ้งเตือน',
        'vi': 'Lỗi khi tải thông báo',
        'fa': 'خطا در بارگذاری اعلان\u200cها',
        'ar': 'خطأ في تحميل الإشعارات',
        'sw': 'Hitilafu katika kupakia arifa',
    },
    'notifications.just_now': {
        'description': 'Just now time ago',
        'en': 'Just now',
        'de': 'Gerade eben',
        'es': 'Ahora mismo',
        'fr': 'À l\'instant',
        'it': 'Proprio ora',
        'pt': 'Agora mesmo',
        'ru': 'Только что',
        'tr': 'Az önce',
        'ka': 'ახლახან',
        'nl': 'Zojuist',
        'sv': 'Just nu',
        'no': 'Akkurat nå',
        'da': 'Lige nu',
        'fi': 'Juuri nyt',
        'pl': 'Właśnie teraz',
        'cs': 'Právě teď',
        'sk': 'Práve teraz',
        'hu': 'Épp most',
        'ro': 'Chiar acum',
        'bg': 'Току-що',
        'el': 'Μόλις τώρα',
        'uk': 'Щойно',
        'zh': '刚刚',
        'ja': 'たった今',
        'ko': '방금',
        'hi': 'अभी',
        'ur': 'ابھی',
        'id': 'Baru saja',
        'ms': 'Baru sahaja',
        'th': 'เมื่อสักครู่',
        'vi': 'Vừa xong',
        'fa': 'همین الان',
        'ar': 'الآن',
        'sw': 'Hivi sasa',
    },
    'notifications.minute_ago': {
        'description': '1 minute ago',
        'en': '1 minute ago',
        'de': 'Vor 1 Minute',
        'es': 'Hace 1 minuto',
        'fr': 'Il y a 1 minute',
        'it': '1 minuto fa',
        'pt': 'Há 1 minuto',
        'ru': '1 минуту назад',
        'tr': '1 dakika önce',
        'ka': '1 წუთის წინ',
        'nl': '1 minuut geleden',
        'sv': 'För 1 minut sedan',
        'no': '1 minutt siden',
        'da': 'For 1 minut siden',
        'fi': '1 minuutti sitten',
        'pl': '1 minutę temu',
        'cs': 'Před 1 minutou',
        'sk': 'Pred 1 minútou',
        'hu': '1 perce',
        'ro': 'Acum 1 minut',
        'bg': 'Преди 1 минута',
        'el': 'Πριν 1 λεπτό',
        'uk': '1 хвилину тому',
        'zh': '1分钟前',
        'ja': '1分前',
        'ko': '1분 전',
        'hi': '1 मिनट पहले',
        'ur': '1 منٹ پہلے',
        'id': '1 menit yang lalu',
        'ms': '1 minit yang lalu',
        'th': '1 นาทีที่แล้ว',
        'vi': '1 phút trước',
        'fa': '1 دقیقه پیش',
        'ar': 'منذ دقيقة واحدة',
        'sw': 'Dakika 1 iliyopita',
    },
    'notifications.minutes_ago': {
        'description': 'X minutes ago',
        'en': '{0} minutes ago',
        'de': 'Vor {0} Minuten',
        'es': 'Hace {0} minutos',
        'fr': 'Il y a {0} minutes',
        'it': '{0} minuti fa',
        'pt': 'Há {0} minutos',
        'ru': '{0} минут назад',
        'tr': '{0} dakika önce',
        'ka': '{0} წუთის წინ',
        'nl': '{0} minuten geleden',
        'sv': 'För {0} minuter sedan',
        'no': '{0} minutter siden',
        'da': 'For {0} minutter siden',
        'fi': '{0} minuuttia sitten',
        'pl': '{0} minut temu',
        'cs': 'Před {0} minutami',
        'sk': 'Pred {0} minútami',
        'hu': '{0} perce',
        'ro': 'Acum {0} minute',
        'bg': 'Преди {0} минути',
        'el': 'Πριν {0} λεπτά',
        'uk': '{0} хвилин тому',
        'zh': '{0}分钟前',
        'ja': '{0}分前',
        'ko': '{0}분 전',
        'hi': '{0} मिनट पहले',
        'ur': '{0} منٹ پہلے',
        'id': '{0} menit yang lalu',
        'ms': '{0} minit yang lalu',
        'th': '{0} นาทีที่แล้ว',
        'vi': '{0} phút trước',
        'fa': '{0} دقیقه پیش',
        'ar': 'منذ {0} دقائق',
        'sw': 'Dakika {0} zilizopita',
    },
    'notifications.hour_ago': {
        'description': '1 hour ago',
        'en': '1 hour ago',
        'de': 'Vor 1 Stunde',
        'es': 'Hace 1 hora',
        'fr': 'Il y a 1 heure',
        'it': '1 ora fa',
        'pt': 'Há 1 hora',
        'ru': '1 час назад',
        'tr': '1 saat önce',
        'ka': '1 საათის წინ',
        'nl': '1 uur geleden',
        'sv': 'För 1 timme sedan',
        'no': '1 time siden',
        'da': 'For 1 time siden',
        'fi': '1 tunti sitten',
        'pl': '1 godzinę temu',
        'cs': 'Před 1 hodinou',
        'sk': 'Pred 1 hodinou',
        'hu': '1 órája',
        'ro': 'Acum 1 oră',
        'bg': 'Преди 1 час',
        'el': 'Πριν 1 ώρα',
        'uk': '1 годину тому',
        'zh': '1小时前',
        'ja': '1時間前',
        'ko': '1시간 전',
        'hi': '1 घंटे पहले',
        'ur': '1 گھنٹہ پہلے',
        'id': '1 jam yang lalu',
        'ms': '1 jam yang lalu',
        'th': '1 ชั่วโมงที่แล้ว',
        'vi': '1 giờ trước',
        'fa': '1 ساعت پیش',
        'ar': 'منذ ساعة واحدة',
        'sw': 'Saa 1 iliyopita',
    },
    'notifications.hours_ago': {
        'description': 'X hours ago',
        'en': '{0} hours ago',
        'de': 'Vor {0} Stunden',
        'es': 'Hace {0} horas',
        'fr': 'Il y a {0} heures',
        'it': '{0} ore fa',
        'pt': 'Há {0} horas',
        'ru': '{0} часов назад',
        'tr': '{0} saat önce',
        'ka': '{0} საათის წინ',
        'nl': '{0} uur geleden',
        'sv': 'För {0} timmar sedan',
        'no': '{0} timer siden',
        'da': 'For {0} timer siden',
        'fi': '{0} tuntia sitten',
        'pl': '{0} godzin temu',
        'cs': 'Před {0} hodinami',
        'sk': 'Pred {0} hodinami',
        'hu': '{0} órája',
        'ro': 'Acum {0} ore',
        'bg': 'Преди {0} часа',
        'el': 'Πριν {0} ώρες',
        'uk': '{0} годин тому',
        'zh': '{0}小时前',
        'ja': '{0}時間前',
        'ko': '{0}시간 전',
        'hi': '{0} घंटे पहले',
        'ur': '{0} گھنٹے پہلے',
        'id': '{0} jam yang lalu',
        'ms': '{0} jam yang lalu',
        'th': '{0} ชั่วโมงที่แล้ว',
        'vi': '{0} giờ trước',
        'fa': '{0} ساعت پیش',
        'ar': 'منذ {0} ساعات',
        'sw': 'Masaa {0} yaliyopita',
    },
    'notifications.day_ago': {
        'description': '1 day ago',
        'en': '1 day ago',
        'de': 'Vor 1 Tag',
        'es': 'Hace 1 día',
        'fr': 'Il y a 1 jour',
        'it': '1 giorno fa',
        'pt': 'Há 1 dia',
        'ru': '1 день назад',
        'tr': '1 gün önce',
        'ka': '1 დღის წინ',
        'nl': '1 dag geleden',
        'sv': 'För 1 dag sedan',
        'no': '1 dag siden',
        'da': 'For 1 dag siden',
        'fi': '1 päivä sitten',
        'pl': '1 dzień temu',
        'cs': 'Před 1 dnem',
        'sk': 'Pred 1 dňom',
        'hu': '1 napja',
        'ro': 'Acum 1 zi',
        'bg': 'Преди 1 ден',
        'el': 'Πριν 1 ημέρα',
        'uk': '1 день тому',
        'zh': '1天前',
        'ja': '1日前',
        'ko': '1일 전',
        'hi': '1 दिन पहले',
        'ur': '1 دن پہلے',
        'id': '1 hari yang lalu',
        'ms': '1 hari yang lalu',
        'th': '1 วันที่แล้ว',
        'vi': '1 ngày trước',
        'fa': '1 روز پیش',
        'ar': 'منذ يوم واحد',
        'sw': 'Siku 1 iliyopita',
    },
    'notifications.days_ago': {
        'description': 'X days ago',
        'en': '{0} days ago',
        'de': 'Vor {0} Tagen',
        'es': 'Hace {0} días',
        'fr': 'Il y a {0} jours',
        'it': '{0} giorni fa',
        'pt': 'Há {0} dias',
        'ru': '{0} дней назад',
        'tr': '{0} gün önce',
        'ka': '{0} დღის წინ',
        'nl': '{0} dagen geleden',
        'sv': 'För {0} dagar sedan',
        'no': '{0} dager siden',
        'da': 'For {0} dage siden',
        'fi': '{0} päivää sitten',
        'pl': '{0} dni temu',
        'cs': 'Před {0} dny',
        'sk': 'Pred {0} dňami',
        'hu': '{0} napja',
        'ro': 'Acum {0} zile',
        'bg': 'Преди {0} дни',
        'el': 'Πριν {0} ημέρες',
        'uk': '{0} днів тому',
        'zh': '{0}天前',
        'ja': '{0}日前',
        'ko': '{0}일 전',
        'hi': '{0} दिन पहले',
        'ur': '{0} دن پہلے',
        'id': '{0} hari yang lalu',
        'ms': '{0} hari yang lalu',
        'th': '{0} วันที่แล้ว',
        'vi': '{0} ngày trước',
        'fa': '{0} روز پیش',
        'ar': 'منذ {0} أيام',
        'sw': 'Siku {0} zilizopita',
    },
}

def migrate():
    try:
        from server.db_config import get_db_connection, get_database_config
        from server.db import upsert_localization_entry
        
        config = get_database_config()
        if config['type'] != 'postgresql':
            print("❌ This script only works with PostgreSQL")
            return
        
        conn = get_db_connection()
        if not conn:
            print("❌ Failed to connect to database")
            return
        
        try:
            print(f"✅ Connected to {config['type']} database")
            
            print(f"\n📝 Adding {len(NOTIFICATION_LOCALIZATIONS)} notification localization entries...")
            for key, translations in NOTIFICATION_LOCALIZATIONS.items():
                print(f"  Adding: {key}")
                payload = {'reference_key': key, **translations}
                upsert_localization_entry(payload, conn=conn)
            
            conn.commit()
            print(f"\n✅ Successfully added all notification localization entries!")
            print(f"   - {len(NOTIFICATION_LOCALIZATIONS)} entries")
            
        except Exception as e:
            print(f"❌ Error: {e}")
            import traceback
            traceback.print_exc()
            conn.rollback()
        finally:
            conn.close()
    except ImportError as e:
        print(f"❌ Import error: {e}")
        print("This script must be run on Railway where dependencies are available.")
        raise

if __name__ == '__main__':
    migrate()


