#!/usr/bin/env python3
"""
Migration script to add new topic localization entries.
Run this on Railway after deployment.
Usage: railway run python3 migrate_topic_localizations.py
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# New topic entries
NEW_TOPICS = {
    'topics.academic': {'description': 'Academic topic', 'en': 'Academic', 'de': 'Studium', 'es': 'Académico', 'fr': 'Académique', 'it': 'Accademico', 'pt': 'Acadêmico', 'ru': 'Академический', 'tr': 'Akademik', 'ka': 'აკადემიური', 'nl': 'Academisch', 'sv': 'Akademisk', 'no': 'Akademisk', 'da': 'Akademisk', 'fi': 'Akateeminen', 'pl': 'Akademicki', 'cs': 'Akademický', 'sk': 'Akademický', 'hu': 'Akadémiai', 'ro': 'Academic', 'bg': 'Академичен', 'el': 'Ακαδημαϊκό', 'uk': 'Академічний', 'zh': '学术', 'ja': '学術', 'ko': '학술', 'hi': 'शैक्षणिक', 'ur': 'تعلیمی', 'id': 'Akademik', 'ms': 'Akademik', 'th': 'วิชาการ', 'vi': 'Học thuật', 'fa': 'آکادمیک', 'ar': 'أكاديمي', 'sw': 'Kielimu'},
    'topics.family': {'description': 'Family topic', 'en': 'Family', 'de': 'Familie', 'es': 'Familia', 'fr': 'Famille', 'it': 'Famiglia', 'pt': 'Família', 'ru': 'Семья', 'tr': 'Aile', 'ka': 'ოჯახი', 'nl': 'Familie', 'sv': 'Familj', 'no': 'Familie', 'da': 'Familie', 'fi': 'Perhe', 'pl': 'Rodzina', 'cs': 'Rodina', 'sk': 'Rodina', 'hu': 'Család', 'ro': 'Familie', 'bg': 'Семейство', 'el': 'Οικογένεια', 'uk': 'Сім\'я', 'zh': '家庭', 'ja': '家族', 'ko': '가족', 'hi': 'परिवार', 'ur': 'خاندان', 'id': 'Keluarga', 'ms': 'Keluarga', 'th': 'ครอบครัว', 'vi': 'Gia đình', 'fa': 'خانواده', 'ar': 'عائلة', 'sw': 'Familia'},
    'topics.immigration': {'description': 'Immigration topic', 'en': 'Immigration', 'de': 'Einwanderung', 'es': 'Inmigración', 'fr': 'Immigration', 'it': 'Immigrazione', 'pt': 'Imigração', 'ru': 'Иммиграция', 'tr': 'Göç', 'ka': 'იმიგრაცია', 'nl': 'Immigratie', 'sv': 'Invandring', 'no': 'Innvandring', 'da': 'Indvandring', 'fi': 'Maahanmuutto', 'pl': 'Imigracja', 'cs': 'Imigrace', 'sk': 'Imigrácia', 'hu': 'Bevándorlás', 'ro': 'Imigrație', 'bg': 'Имиграция', 'el': 'Μετανάστευση', 'uk': 'Імміграція', 'zh': '移民', 'ja': '移民', 'ko': '이민', 'hi': 'आप्रवासन', 'ur': 'ہجرت', 'id': 'Imigrasi', 'ms': 'Imigresen', 'th': 'การเข้าเมือง', 'vi': 'Nhập cư', 'fa': 'مهاجرت', 'ar': 'الهجرة', 'sw': 'Uhamiaji'},
    'topics.culture': {'description': 'Culture topic', 'en': 'Culture', 'de': 'Kultur', 'es': 'Cultura', 'fr': 'Culture', 'it': 'Cultura', 'pt': 'Cultura', 'ru': 'Культура', 'tr': 'Kültür', 'ka': 'კულტურა', 'nl': 'Cultuur', 'sv': 'Kultur', 'no': 'Kultur', 'da': 'Kultur', 'fi': 'Kulttuuri', 'pl': 'Kultura', 'cs': 'Kultura', 'sk': 'Kultúra', 'hu': 'Kultúra', 'ro': 'Cultură', 'bg': 'Култура', 'el': 'Πολιτισμός', 'uk': 'Культура', 'zh': '文化', 'ja': '文化', 'ko': '문화', 'hi': 'संस्कृति', 'ur': 'ثقافت', 'id': 'Budaya', 'ms': 'Budaya', 'th': 'วัฒนธรรม', 'vi': 'Văn hóa', 'fa': 'فرهنگ', 'ar': 'ثقافة', 'sw': 'Utamaduni'},
    'topics.hobbies': {'description': 'Hobbies topic', 'en': 'Hobbies', 'de': 'Hobbys', 'es': 'Pasatiempos', 'fr': 'Loisirs', 'it': 'Hobby', 'pt': 'Passatempos', 'ru': 'Хобби', 'tr': 'Hobiler', 'ka': 'ჰობი', 'nl': 'Hobby\'s', 'sv': 'Hobbys', 'no': 'Hobbyer', 'da': 'Hobbyer', 'fi': 'Harrastukset', 'pl': 'Hobby', 'cs': 'Koníčky', 'sk': 'Koníčky', 'hu': 'Hobbik', 'ro': 'Hobby-uri', 'bg': 'Хобита', 'el': 'Χόμπι', 'uk': 'Хобі', 'zh': '爱好', 'ja': '趣味', 'ko': '취미', 'hi': 'शौक', 'ur': 'شوقیہ', 'id': 'Hobi', 'ms': 'Hobi', 'th': 'งานอดิเรก', 'vi': 'Sở thích', 'fa': 'سرگرمی‌ها', 'ar': 'الهوايات', 'sw': 'Burudani'},
    'topics.healthcare': {'description': 'Healthcare topic', 'en': 'Healthcare', 'de': 'Gesundheitswesen', 'es': 'Salud', 'fr': 'Santé', 'it': 'Sanità', 'pt': 'Saúde', 'ru': 'Здравоохранение', 'tr': 'Sağlık', 'ka': 'ჯანდაცვა', 'nl': 'Gezondheidszorg', 'sv': 'Hälsovård', 'no': 'Helsevesen', 'da': 'Sundhedsvæsen', 'fi': 'Terveydenhuolto', 'pl': 'Opieka zdrowotna', 'cs': 'Zdravotnictví', 'sk': 'Zdravotníctvo', 'hu': 'Egészségügy', 'ro': 'Sănătate', 'bg': 'Здравеопазване', 'el': 'Υγεία', 'uk': 'Охорона здоров\'я', 'zh': '医疗保健', 'ja': '医療', 'ko': '의료', 'hi': 'स्वास्थ्य सेवा', 'ur': 'صحت', 'id': 'Kesehatan', 'ms': 'Penjagaan kesihatan', 'th': 'การดูแลสุขภาพ', 'vi': 'Chăm sóc sức khỏe', 'fa': 'مراقبت‌های بهداشتی', 'ar': 'الرعاية الصحية', 'sw': 'Afya'},
    'topics.technology': {'description': 'Technology topic', 'en': 'Technology', 'de': 'Technologie', 'es': 'Tecnología', 'fr': 'Technologie', 'it': 'Tecnologia', 'pt': 'Tecnologia', 'ru': 'Технология', 'tr': 'Teknoloji', 'ka': 'ტექნოლოგია', 'nl': 'Technologie', 'sv': 'Teknologi', 'no': 'Teknologi', 'da': 'Teknologi', 'fi': 'Teknologia', 'pl': 'Technologia', 'cs': 'Technologie', 'sk': 'Technológia', 'hu': 'Technológia', 'ro': 'Tehnologie', 'bg': 'Технология', 'el': 'Τεχνολογία', 'uk': 'Технологія', 'zh': '技术', 'ja': '技術', 'ko': '기술', 'hi': 'प्रौद्योगिकी', 'ur': 'ٹیکنالوجی', 'id': 'Teknologi', 'ms': 'Teknologi', 'th': 'เทคโนโลยี', 'vi': 'Công nghệ', 'fa': 'فناوری', 'ar': 'التكنولوجيا', 'sw': 'Teknolojia'},
    'topics.romance': {'description': 'Romance topic', 'en': 'Romance', 'de': 'Romantik', 'es': 'Romance', 'fr': 'Romance', 'it': 'Romanticismo', 'pt': 'Romance', 'ru': 'Романтика', 'tr': 'Romantizm', 'ka': 'რომანტიკა', 'nl': 'Romantiek', 'sv': 'Romantik', 'no': 'Romantikk', 'da': 'Romantik', 'fi': 'Romantiikka', 'pl': 'Romans', 'cs': 'Romantika', 'sk': 'Romantika', 'hu': 'Romantika', 'ro': 'Romantism', 'bg': 'Романтика', 'el': 'Ρομαντισμός', 'uk': 'Романтика', 'zh': '浪漫', 'ja': 'ロマンス', 'ko': '로맨스', 'hi': 'रोमांस', 'ur': 'رومانوی', 'id': 'Romantis', 'ms': 'Romantik', 'th': 'ความโรแมนติก', 'vi': 'Lãng mạn', 'fa': 'عاشقانه', 'ar': 'رومانسي', 'sw': 'Mapenzi'},
    'topics.media': {'description': 'Media topic', 'en': 'Media', 'de': 'Medien', 'es': 'Medios', 'fr': 'Médias', 'it': 'Media', 'pt': 'Mídia', 'ru': 'СМИ', 'tr': 'Medya', 'ka': 'მედია', 'nl': 'Media', 'sv': 'Media', 'no': 'Media', 'da': 'Medier', 'fi': 'Media', 'pl': 'Media', 'cs': 'Média', 'sk': 'Médiá', 'hu': 'Média', 'ro': 'Media', 'bg': 'Медии', 'el': 'Μέσα', 'uk': 'Медіа', 'zh': '媒体', 'ja': 'メディア', 'ko': '미디어', 'hi': 'मीडिया', 'ur': 'میڈیا', 'id': 'Media', 'ms': 'Media', 'th': 'สื่อ', 'vi': 'Truyền thông', 'fa': 'رسانه', 'ar': 'الإعلام', 'sw': 'Vyombo vya habari'},
}

ONBOARDING_DESCRIPTIONS = {
    'onboarding.skip': {'description': 'Skip onboarding button', 'en': 'Skip', 'de': 'Überspringen', 'es': 'Omitir', 'fr': 'Passer', 'it': 'Salta', 'pt': 'Pular', 'ru': 'Пропустить', 'tr': 'Atla', 'ka': 'გამოტოვება', 'nl': 'Overslaan', 'sv': 'Hoppa över', 'no': 'Hopp over', 'da': 'Spring over', 'fi': 'Ohita', 'pl': 'Pomiń', 'cs': 'Přeskočit', 'sk': 'Preskočiť', 'hu': 'Kihagyás', 'ro': 'Sări', 'bg': 'Пропусни', 'el': 'Παράλειψη', 'uk': 'Пропустити', 'zh': '跳过', 'ja': 'スキップ', 'ko': '건너뛰기', 'hi': 'छोड़ें', 'ur': 'چھوڑ دیں', 'id': 'Lewati', 'ms': 'Langkau', 'th': 'ข้าม', 'vi': 'Bỏ qua', 'fa': 'رد کردن', 'ar': 'تخطي', 'sw': 'Ruka'},
    'onboarding.welcome.title': {'description': 'Onboarding welcome title', 'en': 'Welcome to Siluma!', 'de': 'Willkommen bei Siluma!', 'es': '¡Bienvenido a Siluma!', 'fr': 'Bienvenue sur Siluma!', 'it': 'Benvenuto su Siluma!', 'pt': 'Bem-vindo ao Siluma!', 'ru': 'Добро пожаловать в Siluma!', 'tr': "Siluma'ya Hoş Geldiniz!", 'ka': 'მოგესალმებით Siluma-ში!', 'nl': 'Welkom bij Siluma!', 'sv': 'Välkommen till Siluma!', 'no': 'Velkommen til Siluma!', 'da': 'Velkommen til Siluma!', 'fi': 'Tervetuloa Silumaan!', 'pl': 'Witamy w Siluma!', 'cs': 'Vítejte v Siluma!', 'sk': 'Vitajte v Siluma!', 'hu': 'Üdvözöljük a Silumában!', 'ro': 'Bun venit la Siluma!', 'bg': 'Добре дошли в Siluma!', 'el': 'Καλώς ήρθατε στο Siluma!', 'uk': 'Ласкаво просимо до Siluma!', 'zh': '欢迎来到 Siluma！', 'ja': 'Silumaへようこそ！', 'ko': 'Siluma에 오신 것을 환영합니다!', 'hi': 'Siluma में आपका स्वागत है!', 'ur': 'Siluma میں خوش آمدید!', 'id': 'Selamat datang di Siluma!', 'ms': 'Selamat datang ke Siluma!', 'th': 'ยินดีต้อนรับสู่ Siluma!', 'vi': 'Chào mừng đến với Siluma!', 'fa': 'به Siluma خوش آمدید!', 'ar': 'مرحباً بك في Siluma!', 'sw': 'Karibu Siluma!'},
    'onboarding.welcome.subtitle': {'description': 'Onboarding welcome subtitle', 'en': "Let's personalize your learning experience in just a few steps.", 'de': 'Lass uns dein Lernerlebnis in nur wenigen Schritten personalisieren.', 'es': 'Personalicemos tu experiencia de aprendizaje en solo unos pasos.', 'fr': "Personnalisons votre expérience d'apprentissage en quelques étapes.", 'it': "Personalizziamo la tua esperienza di apprendimento in pochi passaggi.", 'pt': 'Vamos personalizar sua experiência de aprendizado em apenas algumas etapas.', 'ru': 'Давайте персонализируем ваш опыт обучения всего за несколько шагов.', 'tr': "Öğrenme deneyiminizi birkaç adımda kişiselleştirelim.", 'ka': 'მოდით პერსონალიზაცია გავუკეთოთ თქვენს სწავლის გამოცდილებას რამდენიმე ნაბიჯში.', 'nl': "Laten we je leerervaring in slechts een paar stappen personaliseren.", 'sv': 'Låt oss anpassa din inlärningsupplevelse i bara några steg.', 'no': 'La oss tilpasse læringsopplevelsen din i bare noen få steg.', 'da': 'Lad os tilpasse din læringsoplevelse i kun få trin.', 'fi': 'Mukautetaan oppimiskokemuksesi vain muutamassa vaiheessa.', 'pl': 'Dostosujmy Twoje doświadczenie w nauce w zaledwie kilku krokach.', 'cs': 'Přizpůsobme vaši učební zkušenost v několika krocích.', 'sk': 'Prispôsobme vašu učebnú skúsenosť v niekoľkých krokoch.', 'hu': 'Személyre szabjuk a tanulási élményét csak néhány lépésben.', 'ro': 'Să personalizăm experiența ta de învățare în doar câteva pași.', 'bg': 'Нека персонализираме вашето учебно преживяване само с няколко стъпки.', 'el': 'Ας εξατομικεύσουμε την εμπειρία μάθησής σας σε λίγα βήματα.', 'uk': "Давайте персоналізуємо ваш досвід навчання лише за кілька кроків.", 'zh': '让我们在几个步骤中个性化您的学习体验。', 'ja': 'わずか数ステップで学習体験をパーソナライズしましょう。', 'ko': '몇 단계만으로 학습 경험을 개인화해 보겠습니다.', 'hi': 'आइए कुछ ही चरणों में आपके सीखने के अनुभव को व्यक्तिगत बनाएं।', 'ur': 'آئیے صرف چند مراحل میں آپ کے سیکھنے کے تجربے کو ذاتی بنائیں۔', 'id': 'Mari personalisasikan pengalaman belajar Anda hanya dalam beberapa langkah.', 'ms': 'Mari kita peribadikan pengalaman pembelajaran anda dalam beberapa langkah sahaja.', 'th': 'มาปรับแต่งประสบการณ์การเรียนรู้ของคุณในไม่กี่ขั้นตอน', 'vi': 'Hãy cá nhân hóa trải nghiệm học tập của bạn chỉ trong vài bước.', 'fa': 'بیایید تجربه یادگیری شما را در چند مرحله شخصی‌سازی کنیم.', 'ar': 'دعنا نخصص تجربة التعلم الخاصة بك في خطوات قليلة فقط.', 'sw': 'Wacha tuibadilishe uzoefu wako wa kujifunza katika hatua chache tu.'},
    'onboarding.get_started': {'description': 'Get started button', 'en': 'Get Started', 'de': 'Loslegen', 'es': 'Comenzar', 'fr': 'Commencer', 'it': 'Inizia', 'pt': 'Começar', 'ru': 'Начать', 'tr': 'Başla', 'ka': 'დაწყება', 'nl': 'Aan de slag', 'sv': 'Kom igång', 'no': 'Kom i gang', 'da': 'Kom i gang', 'fi': 'Aloita', 'pl': 'Zacznij', 'cs': 'Začít', 'sk': 'Začať', 'hu': 'Kezdés', 'ro': 'Începe', 'bg': 'Започни', 'el': 'Ξεκινήστε', 'uk': 'Почати', 'zh': '开始', 'ja': '始める', 'ko': '시작하기', 'hi': 'शुरू करें', 'ur': 'شروع کریں', 'id': 'Mulai', 'ms': 'Mula', 'th': 'เริ่มต้น', 'vi': 'Bắt đầu', 'fa': 'شروع کنید', 'ar': 'ابدأ', 'sw': 'Anza'},
    'onboarding.native_language.title': {'description': 'Native language step title', 'en': "What's your native language?", 'de': 'Was ist deine Muttersprache?', 'es': '¿Cuál es tu idioma nativo?', 'fr': "Quelle est votre langue maternelle?", 'it': "Qual è la tua lingua madre?", 'pt': 'Qual é o seu idioma nativo?', 'ru': 'Какой ваш родной язык?', 'tr': 'Anadiliniz nedir?', 'ka': 'რა არის თქვენი მშობლიური ენა?', 'nl': 'Wat is je moedertaal?', 'sv': 'Vad är ditt modersmål?', 'no': 'Hva er ditt morsmål?', 'da': 'Hvad er dit modersmål?', 'fi': 'Mikä on äidinkielesi?', 'pl': 'Jaki jest twój język ojczysty?', 'cs': 'Jaký je váš rodný jazyk?', 'sk': 'Aký je váš rodný jazyk?', 'hu': 'Mi az anyanyelved?', 'ro': 'Care este limba ta maternă?', 'bg': 'Какъв е вашият майчин език?', 'el': 'Ποια είναι η μητρική σας γλώσσα;', 'uk': 'Яка ваша рідна мова?', 'zh': '您的母语是什么？', 'ja': 'あなたの母国語は何ですか？', 'ko': '모국어가 무엇인가요?', 'hi': 'आपकी मातृभाषा क्या है?', 'ur': 'آپ کی مادری زبان کیا ہے؟', 'id': 'Apa bahasa ibu Anda?', 'ms': 'Apakah bahasa ibunda anda?', 'th': 'ภาษาแม่ของคุณคืออะไร?', 'vi': 'Ngôn ngữ mẹ đẻ của bạn là gì?', 'fa': 'زبان مادری شما چیست؟', 'ar': 'ما هي لغتك الأم؟', 'sw': 'Lugha yako ya mama ni nini?'},
    'onboarding.native_language.subtitle': {'description': 'Native language step subtitle', 'en': 'This helps us provide better translations and explanations.', 'de': 'Das hilft uns, bessere Übersetzungen und Erklärungen zu bieten.', 'es': 'Esto nos ayuda a proporcionar mejores traducciones y explicaciones.', 'fr': "Cela nous aide à fournir de meilleures traductions et explications.", 'it': "Questo ci aiuta a fornire traduzioni e spiegazioni migliori.", 'pt': 'Isso nos ajuda a fornecer melhores traduções e explicações.', 'ru': 'Это помогает нам предоставлять лучшие переводы и объяснения.', 'tr': 'Bu, daha iyi çeviriler ve açıklamalar sağlamamıza yardımcı olur.', 'ka': 'ეს გვეხმარება უკეთესი თარგმანებისა და ახსნების მიწოდებაში.', 'nl': 'Dit helpt ons betere vertalingen en uitleg te bieden.', 'sv': 'Detta hjälper oss att ge bättre översättningar och förklaringar.', 'no': 'Dette hjelper oss med å gi bedre oversettelser og forklaringer.', 'da': 'Dette hjælper os med at give bedre oversættelser og forklaringer.', 'fi': 'Tämä auttaa meitä tarjoamaan parempia käännöksiä ja selityksiä.', 'pl': 'Pomaga nam to zapewnić lepsze tłumaczenia i wyjaśnienia.', 'cs': 'To nám pomáhá poskytovat lepší překlady a vysvětlení.', 'sk': 'To nám pomáha poskytovať lepšie preklady a vysvetlenia.', 'hu': 'Ez segít nekünk jobb fordításokat és magyarázatokat nyújtani.', 'ro': 'Acest lucru ne ajută să oferim traduceri și explicații mai bune.', 'bg': 'Това ни помага да предоставяме по-добри преводи и обяснения.', 'el': 'Αυτό μας βοηθά να παρέχουμε καλύτερες μεταφράσεις και εξηγήσεις.', 'uk': 'Це допомагає нам надавати кращі переклади та пояснення.', 'zh': '这有助于我们提供更好的翻译和解释。', 'ja': 'これにより、より良い翻訳と説明を提供できます。', 'ko': '이를 통해 더 나은 번역과 설명을 제공할 수 있습니다.', 'hi': 'यह हमें बेहतर अनुवाद और स्पष्टीकरण प्रदान करने में मदद करता है।', 'ur': 'یہ ہمیں بہتر تراجم اور وضاحتیں فراہم کرنے میں مدد کرتا ہے۔', 'id': 'Ini membantu kami memberikan terjemahan dan penjelasan yang lebih baik.', 'ms': 'Ini membantu kami memberikan terjemahan dan penjelasan yang lebih baik.', 'th': 'สิ่งนี้ช่วยให้เราสามารถให้คำแปลและคำอธิบายที่ดีขึ้น', 'vi': 'Điều này giúp chúng tôi cung cấp bản dịch và giải thích tốt hơn.', 'fa': 'این به ما کمک می‌کند ترجمه‌ها و توضیحات بهتری ارائه دهیم.', 'ar': 'يساعدنا هذا في تقديم ترجمات وتفسيرات أفضل.', 'sw': 'Hii inatusaidia kutoa tafsiri na maelezo bora zaidi.'},
    'onboarding.target_language.title': {'description': 'Target language step title', 'en': 'What would you like to learn?', 'de': 'Was möchtest du lernen?', 'es': '¿Qué te gustaría aprender?', 'fr': "Que souhaitez-vous apprendre?", 'it': 'Cosa vorresti imparare?', 'pt': 'O que você gostaria de aprender?', 'ru': 'Что вы хотели бы изучить?', 'tr': 'Ne öğrenmek istersiniz?', 'ka': 'რის სწავლას გსურთ?', 'nl': 'Wat wil je leren?', 'sv': 'Vad vill du lära dig?', 'no': 'Hva vil du lære?', 'da': 'Hvad vil du gerne lære?', 'fi': 'Mitä haluat oppia?', 'pl': 'Czego chciałbyś się nauczyć?', 'cs': 'Co byste se chtěli naučit?', 'sk': 'Čo by ste sa chceli naučiť?', 'hu': 'Mit szeretne megtanulni?', 'ro': 'Ce ai vrea să înveți?', 'bg': 'Какво бихте искали да научите?', 'el': 'Τι θα θέλατε να μάθετε;', 'uk': 'Що ви хотіли б вивчити?', 'zh': '您想学什么？', 'ja': '何を学びたいですか？', 'ko': '무엇을 배우고 싶으신가요?', 'hi': 'आप क्या सीखना चाहेंगे?', 'ur': 'آپ کیا سیکھنا چاہیں گے؟', 'id': 'Apa yang ingin Anda pelajari?', 'ms': 'Apa yang anda ingin pelajari?', 'th': 'คุณต้องการเรียนอะไร?', 'vi': 'Bạn muốn học gì?', 'fa': 'چه چیزی می‌خواهید یاد بگیرید؟', 'ar': 'ماذا تريد أن تتعلم؟', 'sw': 'Ungependa kujifunza nini?'},
    'onboarding.target_language.subtitle': {'description': 'Target language step subtitle', 'en': 'Choose your target language and current proficiency level.', 'de': 'Wähle deine Zielsprache und dein aktuelles Sprachniveau.', 'es': 'Elige tu idioma objetivo y tu nivel actual de competencia.', 'fr': "Choisissez votre langue cible et votre niveau de compétence actuel.", 'it': "Scegli la tua lingua target e il tuo livello di competenza attuale.", 'pt': 'Escolha seu idioma de destino e seu nível atual de proficiência.', 'ru': 'Выберите целевой язык и текущий уровень владения.', 'tr': 'Hedef dilinizi ve mevcut yeterlilik seviyenizi seçin.', 'ka': 'აირჩიეთ თქვენი სამიზნე ენა და მიმდინარე დონე.', 'nl': 'Kies je doeltaal en je huidige vaardigheidsniveau.', 'sv': 'Välj ditt målspåk och din nuvarande färdighetsnivå.', 'no': 'Velg målspråket ditt og din nåværende ferdighetsnivå.', 'da': 'Vælg dit mål sprog og dit nuværende færdighedsniveau.', 'fi': 'Valitse kohdekielesi ja nykyinen taitotasonsi.', 'pl': 'Wybierz język docelowy i aktualny poziom zaawansowania.', 'cs': 'Vyberte si cílový jazyk a aktuální úroveň znalostí.', 'sk': 'Vyberte si cieľový jazyk a aktuálnu úroveň znalostí.', 'hu': 'Válassza ki a célnyelvét és jelenlegi szintjét.', 'ro': 'Alegeți limba țintă și nivelul actual de competență.', 'bg': 'Изберете целевия си език и текущото ниво на компетентност.', 'el': 'Επιλέξτε τη γλώσσα στόχο σας και το τρέχον επίπεδο ικανότητάς σας.', 'uk': 'Виберіть цільову мову та поточний рівень володіння.', 'zh': '选择您的目标语言和当前熟练程度。', 'ja': '目標言語と現在の習熟度を選択してください。', 'ko': '목표 언어와 현재 실력 수준을 선택하세요.', 'hi': 'अपनी लक्ष्य भाषा और वर्तमान दक्षता स्तर चुनें।', 'ur': 'اپنی ہدف زبان اور موجودہ مہارت کی سطح منتخب کریں۔', 'id': 'Pilih bahasa target Anda dan tingkat kemahiran saat ini.', 'ms': 'Pilih bahasa sasaran anda dan tahap kemahiran semasa.', 'th': 'เลือกภาษาที่ต้องการและระดับความสามารถปัจจุบันของคุณ', 'vi': 'Chọn ngôn ngữ mục tiêu và trình độ hiện tại của bạn.', 'fa': 'زبان هدف و سطح مهارت فعلی خود را انتخاب کنید.', 'ar': 'اختر لغتك المستهدفة ومستوى إتقانك الحالي.', 'sw': 'Chagua lugha yako ya lengo na kiwango chako cha sasa cha ujuzi.'},
    'onboarding.learning_focus.title': {'description': 'Learning focus step title', 'en': "What's your learning focus?", 'de': 'Was ist dein Lernfokus?', 'es': '¿Cuál es tu enfoque de aprendizaje?', 'fr': "Quel est votre objectif d'apprentissage?", 'it': "Qual è il tuo obiettivo di apprendimento?", 'pt': 'Qual é o seu foco de aprendizado?', 'ru': 'Какова ваша цель обучения?', 'tr': 'Öğrenme odağınız nedir?', 'ka': 'რა არის თქვენი სწავლის ფოკუსი?', 'nl': 'Wat is je leerfocus?', 'sv': 'Vad är ditt lärandefokus?', 'no': 'Hva er ditt læringsfokus?', 'da': 'Hvad er dit læringsfokus?', 'fi': 'Mikä on oppimisintosi?', 'pl': 'Jaki jest twój cel nauki?', 'cs': 'Jaký je váš učební cíl?', 'sk': 'Aký je váš učebný cieľ?', 'hu': 'Mi a tanulási célja?', 'ro': 'Care este obiectivul tău de învățare?', 'bg': 'Каква е вашата цел за обучение?', 'el': 'Ποιος είναι ο στόχος μάθησής σας;', 'uk': 'Яка ваша мета навчання?', 'zh': '您的学习重点是什么？', 'ja': 'あなたの学習の焦点は何ですか？', 'ko': '학습 목표가 무엇인가요?', 'hi': 'आपका सीखने का फोकस क्या है?', 'ur': 'آپ کا سیکھنے کا فوکس کیا ہے؟', 'id': 'Apa fokus pembelajaran Anda?', 'ms': 'Apakah fokus pembelajaran anda?', 'th': 'จุดโฟกัสในการเรียนรู้ของคุณคืออะไร?', 'vi': 'Mục tiêu học tập của bạn là gì?', 'fa': 'تمرکز یادگیری شما چیست؟', 'ar': 'ما هو تركيزك على التعلم؟', 'sw': 'Lengo lako la kujifunza ni nini?'},
    'onboarding.learning_focus.subtitle': {'description': 'Learning focus step subtitle', 'en': 'Choose topics that interest you most.', 'de': 'Wähle Themen, die dich am meisten interessieren.', 'es': 'Elige los temas que más te interesen.', 'fr': 'Choisissez les sujets qui vous intéressent le plus.', 'it': 'Scegli gli argomenti che ti interessano di più.', 'pt': 'Escolha os tópicos que mais lhe interessam.', 'ru': 'Выберите темы, которые вас больше всего интересуют.', 'tr': 'En çok ilginizi çeken konuları seçin.', 'ka': 'აირჩიეთ თემები, რომლებიც ყველაზე მეტად გაინტერესებთ.', 'nl': 'Kies onderwerpen die je het meest interesseren.', 'sv': 'Välj ämnen som intresserar dig mest.', 'no': 'Velg emner som interesserer deg mest.', 'da': 'Vælg emner, der interesserer dig mest.', 'fi': 'Valitse aiheet, jotka kiinnostavat sinua eniten.', 'pl': 'Wybierz tematy, które najbardziej Cię interesują.', 'cs': 'Vyberte témata, která vás nejvíce zajímají.', 'sk': 'Vyberte témy, ktoré vás najviac zaujímajú.', 'hu': 'Válassza ki azokat a témákat, amelyek a legjobban érdeklik.', 'ro': 'Alegeți subiectele care vă interesează cel mai mult.', 'bg': 'Изберете теми, които ви интересуват най-много.', 'el': 'Επιλέξτε θέματα που σας ενδιαφέρουν περισσότερο.', 'uk': 'Виберіть теми, які вас найбільше цікавлять.', 'zh': '选择您最感兴趣的主题。', 'ja': '最も興味のあるトピックを選択してください。', 'ko': '가장 관심 있는 주제를 선택하세요.', 'hi': 'वे विषय चुनें जो आपको सबसे अधिक रुचिकर लगते हैं।', 'ur': 'وہ موضوعات منتخب کریں جو آپ کو سب سے زیادہ دلچسپ لگتے ہیں۔', 'id': 'Pilih topik yang paling menarik minat Anda.', 'ms': 'Pilih topik yang paling menarik minat anda.', 'th': 'เลือกหัวข้อที่คุณสนใจมากที่สุด', 'vi': 'Chọn các chủ đề mà bạn quan tâm nhất.', 'fa': 'موضوعاتی را انتخاب کنید که بیشتر به آن‌ها علاقه دارید.', 'ar': 'اختر الموضوعات التي تهمك أكثر.', 'sw': 'Chagua mada ambazo zinakuvutia zaidi.'},
    'onboarding.back': {'description': 'Back button', 'en': 'Back', 'de': 'Zurück', 'es': 'Atrás', 'fr': 'Retour', 'it': 'Indietro', 'pt': 'Voltar', 'ru': 'Назад', 'tr': 'Geri', 'ka': 'უკან', 'nl': 'Terug', 'sv': 'Tillbaka', 'no': 'Tilbake', 'da': 'Tilbage', 'fi': 'Takaisin', 'pl': 'Wstecz', 'cs': 'Zpět', 'sk': 'Späť', 'hu': 'Vissza', 'ro': 'Înapoi', 'bg': 'Назад', 'el': 'Πίσω', 'uk': 'Назад', 'zh': '返回', 'ja': '戻る', 'ko': '뒤로', 'hi': 'वापस', 'ur': 'واپس', 'id': 'Kembali', 'ms': 'Kembali', 'th': 'กลับ', 'vi': 'Quay lại', 'fa': 'بازگشت', 'ar': 'رجوع', 'sw': 'Rudi'},
    'onboarding.next': {'description': 'Next button', 'en': 'Next', 'de': 'Weiter', 'es': 'Siguiente', 'fr': 'Suivant', 'it': 'Avanti', 'pt': 'Próximo', 'ru': 'Далее', 'tr': 'İleri', 'ka': 'შემდეგი', 'nl': 'Volgende', 'sv': 'Nästa', 'no': 'Neste', 'da': 'Næste', 'fi': 'Seuraava', 'pl': 'Dalej', 'cs': 'Další', 'sk': 'Ďalší', 'hu': 'Következő', 'ro': 'Următorul', 'bg': 'Следващ', 'el': 'Επόμενο', 'uk': 'Далі', 'zh': '下一步', 'ja': '次へ', 'ko': '다음', 'hi': 'अगला', 'ur': 'اگلا', 'id': 'Selanjutnya', 'ms': 'Seterusnya', 'th': 'ถัดไป', 'vi': 'Tiếp theo', 'fa': 'بعدی', 'ar': 'التالي', 'sw': 'Ifuatayo'},
    'onboarding.finish': {'description': 'Finish button', 'en': 'Finish Setup', 'de': 'Einrichtung abschließen', 'es': 'Finalizar configuración', 'fr': "Terminer l'installation", 'it': 'Completa configurazione', 'pt': 'Concluir configuração', 'ru': 'Завершить настройку', 'tr': 'Kurulumu Tamamla', 'ka': 'დაყენების დასრულება', 'nl': 'Setup voltooien', 'sv': 'Slutför installation', 'no': 'Fullfør oppsett', 'da': 'Afslut opsætning', 'fi': 'Viimeistele asennus', 'pl': 'Zakończ konfigurację', 'cs': 'Dokončit nastavení', 'sk': 'Dokončiť nastavenie', 'hu': 'Beállítás befejezése', 'ro': 'Finalizează configurarea', 'bg': 'Завърши настройка', 'el': 'Ολοκλήρωση εγκατάστασης', 'uk': 'Завершити налаштування', 'zh': '完成设置', 'ja': 'セットアップを完了', 'ko': '설정 완료', 'hi': 'सेटअप समाप्त करें', 'ur': 'سیٹ اپ مکمل کریں', 'id': 'Selesaikan Pengaturan', 'ms': 'Selesaikan Persediaan', 'th': 'เสร็จสิ้นการตั้งค่า', 'vi': 'Hoàn tất thiết lập', 'fa': 'اتمام راه\u200cاندازی', 'ar': 'إنهاء الإعداد', 'sw': 'Maliza Usanidi'},
    'onboarding.topics.daily_life.desc': {'description': 'Onboarding description for daily life topic', 'en': 'Everyday conversations and situations', 'de': 'Alltägliche Gespräche und Situationen', 'es': 'Conversaciones y situaciones cotidianas', 'fr': 'Conversations et situations quotidiennes', 'it': 'Conversazioni e situazioni quotidiane', 'pt': 'Conversas e situações do dia a dia', 'ru': 'Повседневные разговоры и ситуации', 'tr': 'Günlük konuşmalar ve durumlar', 'ka': 'ყოველდღიური საუბრები და სიტუაციები', 'nl': 'Alledaagse gesprekken en situaties', 'sv': 'Vardagliga samtal och situationer', 'no': 'Hverdagslige samtaler og situasjoner', 'da': 'Hverdagslige samtaler og situationer', 'fi': 'Arkipäiväiset keskustelut ja tilanteet', 'pl': 'Codzienne rozmowy i sytuacje', 'cs': 'Každodenní rozhovory a situace', 'sk': 'Každodenné rozhovory a situácie', 'hu': 'Mindennapi beszélgetések és helyzetek', 'ro': 'Conversații și situații de zi cu zi', 'bg': 'Всекидневни разговори и ситуации', 'el': 'Καθημερινές συνομιλίες και καταστάσεις', 'uk': 'Повсякденні розмови та ситуації', 'zh': '日常对话和情况', 'ja': '日常会話と状況', 'ko': '일상 대화와 상황', 'hi': 'रोजमर्रा की बातचीत और स्थितियां', 'ur': 'روزمرہ گفتگو اور حالات', 'id': 'Percakapan dan situasi sehari-hari', 'ms': 'Perbualan dan situasi harian', 'th': 'บทสนทนาและสถานการณ์ในชีวิตประจำวัน', 'vi': 'Cuộc trò chuyện và tình huống hàng ngày', 'fa': 'مکالمات و موقعیت\u200cهای روزمره', 'ar': 'المحادثات والمواقف اليومية', 'sw': 'Mazungumzo na hali za kila siku'},
    'onboarding.topics.travel.desc': {'description': 'Onboarding description for travel topic', 'en': 'Travel phrases and cultural insights', 'de': 'Reisephrasen und kulturelle Einblicke', 'es': 'Frases de viaje e información cultural', 'fr': 'Phrases de voyage et aperçus culturels', 'it': 'Frasi di viaggio e approfondimenti culturali', 'pt': 'Frases de viagem e insights culturais', 'ru': 'Туристические фразы и культурные особенности', 'tr': 'Seyahat ifadeleri ve kültürel içgörüler', 'ka': 'მოგზაურობის ფრაზები და კულტურული გამოცდილება', 'nl': 'Reisfrasen en culturele inzichten', 'sv': 'Resfraser och kulturella insikter', 'no': 'Reisefraser og kulturelle innsikter', 'da': 'Rejsefraser og kulturelle indsigter', 'fi': 'Matkailulauseet ja kulttuuriset näkökulmat', 'pl': 'Zwroty podróżnicze i spostrzeżenia kulturowe', 'cs': 'Cestovní fráze a kulturní poznatky', 'sk': 'Cestovné frázy a kultúrne poznatky', 'hu': 'Utazási kifejezések és kulturális betekintések', 'ro': 'Fraze de călătorie și perspective culturale', 'bg': 'Пътуване фрази и културни прозрения', 'el': 'Φράσεις ταξιδιού και πολιτιστικές γνώσεις', 'uk': 'Подорожні фрази та культурні інсайти', 'zh': '旅行短语和文化见解', 'ja': '旅行フレーズと文化的洞察', 'ko': '여행 표현과 문화적 통찰', 'hi': 'यात्रा वाक्यांश और सांस्कृतिक अंतर्दृष्टि', 'ur': 'سفر کے جملے اور ثقافتی بصیرتیں', 'id': 'Frasa perjalanan dan wawasan budaya', 'ms': 'Frasa perjalanan dan pandangan budaya', 'th': 'วลีการเดินทางและข้อมูลเชิงวัฒนธรรม', 'vi': 'Cụm từ du lịch và hiểu biết văn hóa', 'fa': 'عبارات سفر و بینش\u200cهای فرهنگی', 'ar': 'عبارات السفر والرؤى الثقافية', 'sw': 'Maneno ya safari na maarifa ya kitamaduni'},
    'onboarding.topics.work.desc': {'description': 'Onboarding description for work topic', 'en': 'Professional communication and business', 'de': 'Professionelle Kommunikation und Geschäft', 'es': 'Comunicación profesional y negocios', 'fr': 'Communication professionnelle et affaires', 'it': 'Comunicazione professionale e business', 'pt': 'Comunicação profissional e negócios', 'ru': 'Профессиональное общение и бизнес', 'tr': 'Profesyonel iletişim ve iş', 'ka': 'პროფესიონალური კომუნიკაცია და ბიზნესი', 'nl': 'Professionele communicatie en zakelijk', 'sv': 'Professionell kommunikation och affärer', 'no': 'Profesjonell kommunikasjon og forretning', 'da': 'Professionel kommunikation og forretning', 'fi': 'Ammatillinen viestintä ja liiketoiminta', 'pl': 'Komunikacja zawodowa i biznes', 'cs': 'Profesionální komunikace a obchod', 'sk': 'Profesionálna komunikácia a obchod', 'hu': 'Professzionális kommunikáció és üzlet', 'ro': 'Comunicare profesională și afaceri', 'bg': 'Професионална комуникация и бизнес', 'el': 'Επαγγελματική επικοινωνία και επιχειρήσεις', 'uk': 'Професійна комунікація та бізнес', 'zh': '专业沟通和商务', 'ja': '専門的なコミュニケーションとビジネス', 'ko': '전문 커뮤니케이션 및 비즈니스', 'hi': 'पेशेवर संचार और व्यापार', 'ur': 'پیشہ ورانہ مواصلت اور کاروبار', 'id': 'Komunikasi profesional dan bisnis', 'ms': 'Komunikasi profesional dan perniagaan', 'th': 'การสื่อสารทางวิชาชีพและธุรกิจ', 'vi': 'Giao tiếp chuyên nghiệp và kinh doanh', 'fa': 'ارتباطات حرفه\u200cای و کسب\u200cوکار', 'ar': 'التواصل المهني والأعمال', 'sw': 'Mawasiliano ya kitaalamu na biashara'},
    'onboarding.topics.academic.desc': {'description': 'Onboarding description for academic topic', 'en': 'Academic learning and education', 'de': 'Akademisches Lernen und Bildung', 'es': 'Aprendizaje académico y educación', 'fr': 'Apprentissage académique et éducation', 'it': 'Apprendimento accademico e istruzione', 'pt': 'Aprendizado acadêmico e educação', 'ru': 'Академическое обучение и образование', 'tr': 'Akademik öğrenme ve eğitim', 'ka': 'აკადემიური სწავლა და განათლება', 'nl': 'Academisch leren en onderwijs', 'sv': 'Akademiskt lärande och utbildning', 'no': 'Akademisk læring og utdanning', 'da': 'Akademisk læring og uddannelse', 'fi': 'Akateeminen oppiminen ja koulutus', 'pl': 'Nauka akademicka i edukacja', 'cs': 'Akademické učení a vzdělávání', 'sk': 'Akademické učenie a vzdelávanie', 'hu': 'Akadémiai tanulás és oktatás', 'ro': 'Învățare academică și educație', 'bg': 'Академично обучение и образование', 'el': 'Ακαδημαϊκή μάθηση και εκπαίδευση', 'uk': 'Академічне навчання та освіта', 'zh': '学术学习和教育', 'ja': '学術的な学習と教育', 'ko': '학술 학습 및 교육', 'hi': 'शैक्षणिक सीख और शिक्षा', 'ur': 'تعلیمی سیکھنا اور تعلیم', 'id': 'Pembelajaran akademik dan pendidikan', 'ms': 'Pembelajaran akademik dan pendidikan', 'th': 'การเรียนรู้ทางวิชาการและการศึกษา', 'vi': 'Học tập và giáo dục học thuật', 'fa': 'یادگیری و آموزش آکادمیک', 'ar': 'التعلم الأكاديمي والتعليم', 'sw': 'Kujifunza kitaaluma na elimu'},
    'onboarding.topics.family.desc': {'description': 'Onboarding description for family topic', 'en': 'Family relationships and communication', 'de': 'Familienbeziehungen und Kommunikation', 'es': 'Relaciones familiares y comunicación', 'fr': 'Relations familiales et communication', 'it': 'Relazioni familiari e comunicazione', 'pt': 'Relações familiares e comunicação', 'ru': 'Семейные отношения и общение', 'tr': 'Aile ilişkileri ve iletişim', 'ka': 'ოჯახური ურთიერთობები და კომუნიკაცია', 'nl': 'Familierelaties en communicatie', 'sv': 'Familjerelationer och kommunikation', 'no': 'Familierelasjoner og kommunikasjon', 'da': 'Familierelationer og kommunikation', 'fi': 'Perhesuhteet ja viestintä', 'pl': 'Relacje rodzinne i komunikacja', 'cs': 'Rodinné vztahy a komunikace', 'sk': 'Rodinné vzťahy a komunikácia', 'hu': 'Családi kapcsolatok és kommunikáció', 'ro': 'Relații de familie și comunicare', 'bg': 'Семейни отношения и комуникация', 'el': 'Οικογενειακές σχέσεις και επικοινωνία', 'uk': 'Сімейні стосунки та спілкування', 'zh': '家庭关系和沟通', 'ja': '家族関係とコミュニケーション', 'ko': '가족 관계 및 소통', 'hi': 'पारिवारिक रिश्ते और संचार', 'ur': 'خاندانی تعلقات اور مواصلت', 'id': 'Hubungan keluarga dan komunikasi', 'ms': 'Hubungan keluarga dan komunikasi', 'th': 'ความสัมพันธ์ในครอบครัวและการสื่อสาร', 'vi': 'Mối quan hệ gia đình và giao tiếp', 'fa': 'روابط خانوادگی و ارتباطات', 'ar': 'العلاقات الأسرية والتواصل', 'sw': 'Uhusiano wa familia na mawasiliano'},
    'onboarding.topics.immigration.desc': {'description': 'Onboarding description for immigration topic', 'en': 'Living in a new country', 'de': 'Leben in einem neuen Land', 'es': 'Vivir en un nuevo país', 'fr': 'Vivre dans un nouveau pays', 'it': 'Vivere in un nuovo paese', 'pt': 'Viver em um novo país', 'ru': 'Жизнь в новой стране', 'tr': 'Yeni bir ülkede yaşamak', 'ka': 'ახალ ქვეყანაში ცხოვრება', 'nl': 'Leven in een nieuw land', 'sv': 'Leva i ett nytt land', 'no': 'Bo i et nytt land', 'da': 'At bo i et nyt land', 'fi': 'Eläminen uudessa maassa', 'pl': 'Życie w nowym kraju', 'cs': 'Život v nové zemi', 'sk': 'Život v novej krajine', 'hu': 'Új országban élés', 'ro': 'Trăirea într-o țară nouă', 'bg': 'Живот в нова страна', 'el': 'Ζώντας σε μια νέα χώρα', 'uk': 'Життя в новій країні', 'zh': '在新国家生活', 'ja': '新しい国での生活', 'ko': '새로운 국가에서 살기', 'hi': 'एक नए देश में रहना', 'ur': 'ایک نئے ملک میں رہنا', 'id': 'Hidup di negara baru', 'ms': 'Hidup di negara baharu', 'th': 'การใช้ชีวิตในประเทศใหม่', 'vi': 'Sống ở một đất nước mới', 'fa': 'زندگی در یک کشور جدید', 'ar': 'العيش في بلد جديد', 'sw': 'Kuishi katika nchi mpya'},
    'onboarding.topics.culture.desc': {'description': 'Onboarding description for culture topic', 'en': 'Cultural understanding and traditions', 'de': 'Kulturelles Verständnis und Traditionen', 'es': 'Comprensión cultural y tradiciones', 'fr': 'Compréhension culturelle et traditions', 'it': 'Comprensione culturale e tradizioni', 'pt': 'Compreensão cultural e tradições', 'ru': 'Культурное понимание и традиции', 'tr': 'Kültürel anlayış ve gelenekler', 'ka': 'კულტურული გაგება და ტრადიციები', 'nl': 'Cultureel begrip en tradities', 'sv': 'Kulturell förståelse och traditioner', 'no': 'Kulturell forståelse og tradisjoner', 'da': 'Kulturel forståelse og traditioner', 'fi': 'Kulttuurinen ymmärrys ja perinteet', 'pl': 'Zrozumienie kulturowe i tradycje', 'cs': 'Kulturní porozumění a tradice', 'sk': 'Kultúrne porozumenie a tradície', 'hu': 'Kulturális megértés és hagyományok', 'ro': 'Înțelegere culturală și tradiții', 'bg': 'Културно разбиране и традиции', 'el': 'Κατανόηση πολιτισμού και παραδόσεις', 'uk': 'Культурне розуміння та традиції', 'zh': '文化理解和传统', 'ja': '文化的理解と伝統', 'ko': '문화적 이해와 전통', 'hi': 'सांस्कृतिक समझ और परंपराएं', 'ur': 'ثقافتی سمجھ اور روایات', 'id': 'Pemahaman budaya dan tradisi', 'ms': 'Pemahaman budaya dan tradisi', 'th': 'ความเข้าใจทางวัฒนธรรมและประเพณี', 'vi': 'Hiểu biết văn hóa và truyền thống', 'fa': 'درک فرهنگی و سنت‌ها', 'ar': 'الفهم الثقافي والتقاليد', 'sw': 'Uelewa wa kitamaduni na mila'},
    'onboarding.topics.hobbies.desc': {'description': 'Onboarding description for hobbies topic', 'en': 'Leisure activities and interests', 'de': 'Freizeitaktivitäten und Interessen', 'es': 'Actividades de ocio e intereses', 'fr': 'Activités de loisirs et intérêts', 'it': 'Attività ricreative e interessi', 'pt': 'Atividades de lazer e interesses', 'ru': 'Досуг и интересы', 'tr': 'Boş zaman aktiviteleri ve ilgi alanları', 'ka': 'დასვენების აქტივობები და ინტერესები', 'nl': 'Vrijetijdsactiviteiten en interesses', 'sv': 'Fritidsaktiviteter och intressen', 'no': 'Fritidsaktiviteter og interesser', 'da': 'Fritidsaktiviteter og interesser', 'fi': 'Vapaa-ajan aktiviteetit ja kiinnostuksen kohteet', 'pl': 'Zajęcia rekreacyjne i zainteresowania', 'cs': 'Volnočasové aktivity a zájmy', 'sk': 'Voľnočasové aktivity a záujmy', 'hu': 'Szabadidős tevékenységek és érdeklődési körök', 'ro': 'Activități de agrement și interese', 'bg': 'Досугови дейности и интереси', 'el': 'Δραστηριότητες αναψυχής και ενδιαφέροντα', 'uk': 'Дозвілля та інтереси', 'zh': '休闲活动和兴趣', 'ja': 'レジャー活動と興味', 'ko': '여가 활동 및 관심사', 'hi': 'अवकाश गतिविधियां और रुचियां', 'ur': 'تفریحی سرگرمیاں اور دلچسپیاں', 'id': 'Aktivitas rekreasi dan minat', 'ms': 'Aktiviti rekreasi dan minat', 'th': 'กิจกรรมยามว่างและความสนใจ', 'vi': 'Hoạt động giải trí và sở thích', 'fa': 'فعالیت‌های تفریحی و علایق', 'ar': 'أنشطة الترفيه والاهتمامات', 'sw': 'Shughuli za burudani na maslahi'},
    'onboarding.topics.healthcare.desc': {'description': 'Onboarding description for healthcare topic', 'en': 'Medical communication', 'de': 'Medizinische Kommunikation', 'es': 'Comunicación médica', 'fr': 'Communication médicale', 'it': 'Comunicazione medica', 'pt': 'Comunicação médica', 'ru': 'Медицинское общение', 'tr': 'Tıbbi iletişim', 'ka': 'სამედიცინო კომუნიკაცია', 'nl': 'Medische communicatie', 'sv': 'Medicinsk kommunikation', 'no': 'Medisinsk kommunikasjon', 'da': 'Medicinsk kommunikation', 'fi': 'Lääketieteellinen viestintä', 'pl': 'Komunikacja medyczna', 'cs': 'Lékařská komunikace', 'sk': 'Lekárska komunikácia', 'hu': 'Orvosi kommunikáció', 'ro': 'Comunicare medicală', 'bg': 'Медицинска комуникация', 'el': 'Ιατρική επικοινωνία', 'uk': 'Медична комунікація', 'zh': '医疗沟通', 'ja': '医療コミュニケーション', 'ko': '의료 소통', 'hi': 'चिकित्सा संचार', 'ur': 'طبی مواصلت', 'id': 'Komunikasi medis', 'ms': 'Komunikasi perubatan', 'th': 'การสื่อสารทางการแพทย์', 'vi': 'Giao tiếp y tế', 'fa': 'ارتباطات پزشکی', 'ar': 'التواصل الطبي', 'sw': 'Mawasiliano ya kimatibabu'},
    'onboarding.topics.technology.desc': {'description': 'Onboarding description for technology topic', 'en': 'IT and digital communication', 'de': 'IT und digitale Kommunikation', 'es': 'TI y comunicación digital', 'fr': 'Informatique et communication numérique', 'it': 'IT e comunicazione digitale', 'pt': 'TI e comunicação digital', 'ru': 'ИТ и цифровая коммуникация', 'tr': 'BT ve dijital iletişim', 'ka': 'IT და ციფრული კომუნიკაცია', 'nl': 'IT en digitale communicatie', 'sv': 'IT och digital kommunikation', 'no': 'IT og digital kommunikasjon', 'da': 'IT og digital kommunikation', 'fi': 'IT ja digitaalinen viestintä', 'pl': 'IT i komunikacja cyfrowa', 'cs': 'IT a digitální komunikace', 'sk': 'IT a digitálna komunikácia', 'hu': 'IT és digitális kommunikáció', 'ro': 'IT și comunicare digitală', 'bg': 'ИТ и цифрова комуникация', 'el': 'Τεχνολογία πληροφοριών και ψηφιακή επικοινωνία', 'uk': 'IT та цифрова комунікація', 'zh': 'IT和数字通信', 'ja': 'ITとデジタルコミュニケーション', 'ko': 'IT 및 디지털 커뮤니케이션', 'hi': 'आईटी और डिजिटल संचार', 'ur': 'IT اور ڈیجیٹل مواصلت', 'id': 'IT dan komunikasi digital', 'ms': 'IT dan komunikasi digital', 'th': 'IT และการสื่อสารดิจิทัล', 'vi': 'CNTT và giao tiếp kỹ thuật số', 'fa': 'فناوری اطلاعات و ارتباطات دیجیتال', 'ar': 'تقنية المعلومات والتواصل الرقمي', 'sw': 'IT na mawasiliano ya kidijitali'},
    'onboarding.topics.romance.desc': {'description': 'Onboarding description for romance topic', 'en': 'Dating and romantic relationships', 'de': 'Dating und romantische Beziehungen', 'es': 'Citas y relaciones románticas', 'fr': 'Rencontres et relations romantiques', 'it': 'Appuntamenti e relazioni romantiche', 'pt': 'Namoro e relacionamentos românticos', 'ru': 'Знакомства и романтические отношения', 'tr': 'Flört ve romantik ilişkiler', 'ka': 'შეხვედრები და რომანტიკული ურთიერთობები', 'nl': 'Daten en romantische relaties', 'sv': 'Dejting och romantiska relationer', 'no': 'Dating og romantiske forhold', 'da': 'Dating og romantiske forhold', 'fi': 'Seurustelu ja romanttiset suhteet', 'pl': 'Randki i relacje romantyczne', 'cs': 'Rande a romantické vztahy', 'sk': 'Rande a romantické vzťahy', 'hu': 'Randevúk és romantikus kapcsolatok', 'ro': 'Întâlniri și relații romantice', 'bg': 'Срещи и романтични отношения', 'el': 'Ραντεβού και ρομαντικές σχέσεις', 'uk': 'Побачення та романтичні стосунки', 'zh': '约会和浪漫关系', 'ja': 'デートとロマンチックな関係', 'ko': '데이트와 로맨틱한 관계', 'hi': 'डेटिंग और रोमांटिक रिश्ते', 'ur': 'ڈیٹنگ اور رومانوی تعلقات', 'id': 'Kencan dan hubungan romantis', 'ms': 'Berkencan dan hubungan romantik', 'th': 'การเดทและความสัมพันธ์โรแมนติก', 'vi': 'Hẹn hò và mối quan hệ lãng mạn', 'fa': 'دوستیابی و روابط عاشقانه', 'ar': 'المواعدة والعلاقات الرومانسية', 'sw': 'Kupatana na uhusiano wa kimapenzi'},
    'onboarding.topics.media.desc': {'description': 'Onboarding description for media topic', 'en': 'Movies, music and entertainment', 'de': 'Filme, Musik und Unterhaltung', 'es': 'Películas, música y entretenimiento', 'fr': 'Films, musique et divertissement', 'it': 'Film, musica e intrattenimento', 'pt': 'Filmes, música e entretenimento', 'ru': 'Фильмы, музыка и развлечения', 'tr': 'Filmler, müzik ve eğlence', 'ka': 'ფილმები, მუსიკა და გასართობი', 'nl': 'Films, muziek en entertainment', 'sv': 'Filmer, musik och underhållning', 'no': 'Filmer, musikk og underholdning', 'da': 'Film, musik og underholdning', 'fi': 'Elokuvat, musiikki ja viihde', 'pl': 'Filmy, muzyka i rozrywka', 'cs': 'Filmy, hudba a zábava', 'sk': 'Filmy, hudba a zábava', 'hu': 'Filmek, zene és szórakoztatás', 'ro': 'Filme, muzică și divertisment', 'bg': 'Филми, музика и развлечение', 'el': 'Ταινίες, μουσική και ψυχαγωγία', 'uk': 'Фільми, музика та розваги', 'zh': '电影、音乐和娱乐', 'ja': '映画、音楽、エンターテインメント', 'ko': '영화, 음악 및 엔터테인먼트', 'hi': 'फिल्में, संगीत और मनोरंजन', 'ur': 'فلمیں، موسیقی اور تفریح', 'id': 'Film, musik dan hiburan', 'ms': 'Filem, muzik dan hiburan', 'th': 'ภาพยนตร์ ดนตรี และความบันเทิง', 'vi': 'Phim, âm nhạc và giải trí', 'fa': 'فیلم، موسیقی و سرگرمی', 'ar': 'الأفلام والموسيقى والترفيه', 'sw': 'Filamu, muziki na burudani'},
}

def migrate():
    try:
        from server.db_config import get_db_connection, get_database_config
        from server.db import upsert_localization_entry
        
        config = get_database_config()
        if config['type'] != 'postgresql':
            print("❌ This script only works with PostgreSQL")
            return
        
        conn = get_db_connection()
        if not conn:
            print("❌ Failed to connect to database")
            return
        
        try:
            print(f"✅ Connected to {config['type']} database")
            
            all_entries = {**NEW_TOPICS, **ONBOARDING_DESCRIPTIONS}
            
            print(f"\n📝 Adding {len(all_entries)} localization entries...")
            for key, translations in all_entries.items():
                print(f"  Adding: {key}")
                payload = {'reference_key': key, **translations}
                upsert_localization_entry(payload, conn=conn)
            
            conn.commit()
            print(f"\n✅ Successfully added all localization entries!")
            print(f"   - {len(NEW_TOPICS)} topic entries")
            print(f"   - {len(ONBOARDING_DESCRIPTIONS)} onboarding description entries")
            
        except Exception as e:
            print(f"❌ Error: {e}")
            import traceback
            traceback.print_exc()
            conn.rollback()
        finally:
            conn.close()
    except ImportError as e:
        print(f"❌ Import error: {e}")
        print("This script must be run on Railway where dependencies are available.")
        raise

if __name__ == '__main__':
    migrate()
